# Example 1: Simple Local File Creation
# This is a basic example that creates a local file

terraform {
  required_version = ">= 1.0"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

resource "local_file" "welcome" {
  filename = "${path.module}/output/welcome.txt"
  content  = "Welcome to Terraform! This file was created by Infrastructure as Code."
}

resource "local_file" "info" {
  filename = "${path.module}/output/info.txt"
  content  = <<-EOT
    Terraform Configuration Information
    ====================================
    
    This file was generated by Terraform.
    
    Key Concepts Demonstrated:
    - Resource creation
    - Heredoc syntax (<<-EOT)
    - Path module variable
    
    Learn more at: https://www.terraform.io
  EOT
}
