# Example 2: Multiple Resources with Dependencies
# This demonstrates how Terraform handles resource dependencies

terraform {
  required_version = ">= 1.0"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

# Create configuration file
resource "local_file" "config" {
  filename = "${path.module}/project/config.json"
  content = jsonencode({
    application = "terraform-demo"
    version     = "1.0.0"
    environment = "development"
    features = {
      logging = true
      metrics = true
    }
  })
}

# Create data file
resource "local_file" "data" {
  filename = "${path.module}/project/data.txt"
  content  = "Sample data for the application\nLine 2: More data\nLine 3: Even more data"
}

# Create README that references other files
resource "local_file" "readme" {
  filename = "${path.module}/project/README.md"
  content  = <<-EOT
    # Terraform Demo Project
    
    This project was created using Terraform.
    
    ## Files Created
    
    - Configuration: ${local_file.config.filename}
    - Data File: ${local_file.data.filename}
    
    ## About
    
    This demonstrates:
    1. Multiple resource creation
    2. Resource dependencies
    3. JSON encoding with jsonencode()
    4. File references using resource attributes
    
    Generated by Terraform!
  EOT
}
